### ISSUE TITLE
Change palette parameter

### ISSUE THREAD

**Issue by BugliL** [Schrodinger-Hat/ImageGoNord-cli#26]
To specify the palette and colors this is the actual syntax

```shell
~$ image-go-nord -i=file_1.png -o=file_output.png --nord=Aurora,PolarNight
~$ image-go-nord -i=file_1.png -o=file_output.png --monokai
```

I think that could be better and easier to implement and maintain this syntax:

```shell
~$ image-go-nord -i=file_1.png -o=file_output.png --palette nord --colors Aurora
~$ image-go-nord -i=file_1.png -o=file_output.png --palette nord --colors Aurora PolarNight
~$ image-go-nord -i=file_1.png -o=file_output.png --palette monokai
```

```shell
~$ image-go-nord -i=file_1.png -o=file_output.png -p nord -c Aurora
~$ image-go-nord -i=file_1.png -o=file_output.png -p nord -c Aurora PolarNight
~$ image-go-nord -i=file_1.png -o=file_output.png -p monokai
```

**Comment by TheJoin95** [comment]
Overall, I agree. It could be useful to have also a choice interface, directly from a list. 

And what happen in the case of a user is specifying more HEX colors?

**Comment by Wabri** [comment]
Yes, the first version o the cli wasn't made  for several palette, now we should consider as a core feature of it.

Little typo on the leader command `image-go-nord` with d not with t.

Do we want to use this long version or maybe consider to shorten with something like this `ign -i=... -o=... `?

**Comment by BugliL** [comment]
> maybe consider to shorten with something like this ign -i=... -o=... ?
I agree with it, we could do another issue for it

**Comment by BugliL** [comment]
> It could be useful to have also a choice interface, directly from a list.

I think is enough the parameters, maybe, if someone misspelled the name, we could list all available palettes to show which one the user could use.
